### ISSUE TITLE
Work with smaller monitors

### ISSUE THREAD

**Issue by 64bakerst** [YU000jp/logseq-page-tags-and-hierarchy#1]
How can I make this work with smaller monitors? 

I've tried editing first few lines to 
```
/* Screen size */
@media screen and (min-width: 800px) 
```

Still doesn't work.

Just trying to get the Hierarchy and Reference panels to the right side.

**Comment by 64bakerst** [comment]
I hadn't realized Logseq wasn't updated. Missed a lot while I was gone. Works OK - thanks

**Comment by YU000jp** [comment]
Sorry, I had no idea how to display it on a small monitor, so I limited the monitor size.
I'll try to update when I have an idea how to make it happen.

**Comment by YU000jp** [comment]
https://github.com/YU000jp/logseq-page-tags-and-hierarchy/releases/tag/0.0.4
It's done! Please update.
