### ISSUE TITLE
Broken layout on Macbook M1 screen

### ISSUE THREAD

**Issue by gismeteoxoyk** [YU000jp/logseq-page-tags-and-hierarchy#18]
Big monitor:
![Screenshot 2023-07-05 at 12 25 09](https://github.com/YU000jp/logseq-page-tags-and-hierarchy/assets/45935494/683621da-c883-4e87-8b97-ebe063216534)
Macbook M1 monitor:
<img width="1706" alt="Screenshot 2023-07-05 at 12 24 58" src="https://github.com/YU000jp/logseq-page-tags-and-hierarchy/assets/45935494/4de88736-e588-4b65-b54b-d2032105ec7c">

Something with css-styles. 

UDP: After quick research I've found that the problem apparently in 
`@media screen and (min-width: 1560px)`. Where is no any rule for screens with less width, and it doesn't show up correctly.

**Comment by YU000jp** [comment]
Thank you for the report. I have addressed it in the latest release. It was a bug that occurred due to a recent change.
