### ISSUE TITLE
Latest update corrupts page layout, creates multiple columns

### ISSUE THREAD

**Issue by BlakeLeBlancGuernsey** [YU000jp/logseq-page-tags-and-hierarchy#26]
Hello!

Starting up Logseq today and it seems the plugin may be changing how journal pages are being displayed.

Previously, the Tag and Hierarchy "box" would display in the lower right hand corner. 

Today, it is displaying in the upper right hand corner and altering the layout of the page.

Here's a comparison:

![image](https://github.com/YU000jp/logseq-page-tags-and-hierarchy/assets/137244464/364da086-4047-442c-a568-a5711d494ed7)

If it helps, here is a list of plugins I currently have enabled:

```
{
 :logseq-heatmap {:version "v2.4.3", :repo "pengx17/logseq-plugin-heatmap", :effect true, :theme false}
 :logseq-agenda {:version "v2.15.4", :repo "haydenull/logseq-plugin-agenda", :effect true, :theme false}
 :logseq-todo-plugin {:version "v1.12.1", :repo "ahonn/logseq-plugin-todo", :effect true, :theme false}
 :logseq-vim-shortcuts {:version "v0.1.19", :repo "vipzhicheng/logseq-plugin-vim-shortcuts", :effect true, :theme false}
 :logseq-awesome-ui {:version "v2.2.6", :repo "yoyurec/logseq-awesome-ui", :effect true, :theme false}
 :logseq-awesome-styler {:version "v3.7.1", :repo "yoyurec/logseq-awesome-styler", :effect true, :theme false}
 :logseq-fenced-code-plus {:version "0.0.7", :repo "xyhp915/logseq-fenced-code-plus", :effect true, :theme false}
 :logseq-awesome-props {:version "v1.10.0", :repo "yoyurec/logseq-awesome-props", :effect true, :theme false}
 :logseq-awesome-content {:version "v1.2.1", :repo "yoyurec/logseq-awesome-content", :effect true, :theme false}
 :logseq-awesome-links {:version "v1.15.16", :repo "yoyurec/logseq-awesome-links", :effect true, :theme false}
 :logseq-tidy-blocks-plugin {:version "v.1.2.0", :repo "vyleung/logseq-tidy-blocks-plugin", :effect true, :theme false}
 :logseq-tocgen {:version "v2.10.9", :repo "sethyuan/logseq-plugin-tocgen", :effect true, :theme false}
 :logseq-page-tags-and-hierarchy {:version "v2.6.0", :repo "YU000jp/logseq-page-tags-and-hierarchy", :effect true, :theme false}
 :logseq-tabs {:version "v1.19.1", :repo "pengx17/logseq-plugin-tabs", :effect true, :theme false}
 :logseq-copy-code-plugin {:version "v.1.2.0", :repo "vyleung/logseq-copy-code-plugin", :effect true, :theme false}
 }
```

Let me know if there's anything I can do, thanks again for your great plugin!

**Comment by YU000jp** [comment]
As a log for processing

If `Awesome Styler` plugin is enabled
![image](https://github.com/YU000jp/logseq-page-tags-and-hierarchy/assets/111847207/c5d47f4b-e55a-42e6-a50e-a7705ed38d4b)
With `Awesome Styler`

**Comment by YU000jp** [comment]
I released for this bug. Please use new version.

**Comment by BlakeLeBlancGuernsey** [comment]
Thank you @YU000jp !

So it *DOES* fix the problem. BUT! When I first installed the new update and restarted Logseq, the problem was still there.

In order for it to correct, I had to change the position to `bottom`, then change it back to `side`.

Now it's working great!
