### ISSUE TITLE
Request: Title without Namespace

### ISSUE THREAD

**Issue by Hackmodford** [YU000jp/logseq-page-tags-and-hierarchy#38]
Your plugin almost does what I wish.

Current result:
<img width="876" alt="image" src="https://github.com/YU000jp/logseq-page-tags-and-hierarchy/assets/326668/967c30fa-d466-4aa7-9ade-d1668a0f2562">

Desired result:
![image](https://github.com/YU000jp/logseq-page-tags-and-hierarchy/assets/326668/54ade5ac-5166-4c08-a8c3-f53dc1444460)

Could the plugin be modified to simplify the displayed page title instead of having the complete namespace? (see example image)

Ideally if I clicked the title the full title would appear "A/B/C" when editing but when not editing only "C" would be displayed with the links "A/B" above the title.

Also, can the namespace links preserve the capitalization?

If this is not possible let me know.

Thanks

**Comment by YU000jp** [comment]
I released. 

- Removed namespaces from page titles.
- Preserved the capitalization of namespace links.

Thanks to what you've written here, I've been able to feel motivated to make those things a reality. 🆗

**Comment by Hackmodford** [comment]
It’s perfect now. Wish I could have it on mobile now. But thanks!
