### ISSUE TITLE
hope to be able to set it show only up to the first level of sub-level tags

### ISSUE THREAD

**Issue by zqinmiao** [YU000jp/logseq-page-tags-and-hierarchy#40]
## For example：

write a tags
```
#first-level/second-level/three-level
```

Hierarchy view shows all the tags

<img width="299" alt="image" src="https://github.com/YU000jp/logseq-page-tags-and-hierarchy/assets/12278003/a1090347-1bce-4484-8e90-dd7e3e1dd9e8">

## Hope
Hope to be able to set it show only up to the first level of sub-level tags.

Because once there are too many tags, it will cause difficulty in retrieval.

<img width="345" alt="image" src="https://github.com/YU000jp/logseq-page-tags-and-hierarchy/assets/12278003/6247aef2-e115-4cfd-8c23-ce193813255c">

**Comment by YU000jp** [comment]
Thank you for the easy to understand explanation. I'll try to see.

**Comment by YU000jp** [comment]
Succeeded. I release a new version. The default is false, so set it to true.
![image](https://github.com/YU000jp/logseq-page-tags-and-hierarchy/assets/111847207/4c48c658-e6b0-47fa-9a42-bb0ba39a9b65)

**Comment by zqinmiao** [comment]
> Succeeded. I release a new version. The default is false, so set it to true.
> 
> Plugin settings: ![image](https://user-images.githubusercontent.com/111847207/275793430-4c48c658-e6b0-47fa-9a42-bb0ba39a9b65.png)

Thank you very much! ❤️

**Comment by zqinmiao** [comment]
I set it to `true`

<img width="502" alt="image" src="https://github.com/YU000jp/logseq-page-tags-and-hierarchy/assets/12278003/aaf82626-37e6-4b34-9d74-f0ae46b329cf">

But,does not appear to be in effect. `three-level` should not show.
<img width="885" alt="image" src="https://github.com/YU000jp/logseq-page-tags-and-hierarchy/assets/12278003/e8ca08fe-0682-4f76-a808-9110f3252faa">

**Comment by YU000jp** [comment]
It was a bug. I released a new version now.

**Comment by zqinmiao** [comment]
> It was a bug. I released a new version now.

The latest version, I tried it and it didn't change

![iShot_2023-10-18_14 03 15](https://github.com/YU000jp/logseq-page-tags-and-hierarchy/assets/12278003/7f0ec12e-0b88-482f-b86a-a105cc59617a)

**Comment by YU000jp** [comment]
There were also other errors in processing. Currently, only cases that include / such as A/B are processed. Sorry.

**Comment by YU000jp** [comment]
Fixed what I know at the moment. Please try again.

**Comment by zqinmiao** [comment]
> Fixed what I know at the moment. Please try again.

It's all right now. Thank you very much. ❤️
