### ISSUE TITLE
Comma stops the parsing

### ISSUE THREAD

**Issue by stdword** [YU000jp/logseq-page-tags-and-hierarchy#44]
# Demo
<img width="800px" src="https://github.com/YU000jp/logseq-page-tags-and-hierarchy/assets/1984175/53d40ecb-63e0-45f8-ac6d-61e1512147fd"/>

**Comment by YU000jp** [comment]
That was indeed a bug. (User date formats may contain `/` and `,`. In that case, it was necessary to check with the journal flag.)

I released a new version. Please update.
Thanks.

**Comment by stdword** [comment]
Checked: it fixed! Thank you ❤️
