### ISSUE TITLE
Enable booleanHierarchyForFirstLevelOnly option, link display is missing.

### ISSUE THREAD

**Issue by zqinmiao** [YU000jp/logseq-page-tags-and-hierarchy#46]
Enable booleanHierarchyForFirstLevelOnly option. When the label hierarchy is greater than 4, the following hierarchy cannot be displayed.

## My setup is as follows
<img width="628" alt="image" src="https://github.com/YU000jp/logseq-page-tags-and-hierarchy/assets/12278003/dc8fa939-a318-40ed-a977-b6a96c196e18">

## My tag structure

`[[first-level/second-level/three-level/four-level]]`

<img width="402" alt="image" src="https://github.com/YU000jp/logseq-page-tags-and-hierarchy/assets/12278003/8b7891c3-cffb-42d0-9a27-9d3a3b0505ed">

When I go to three-level, Hierarchy doesn't show four-level.
<img width="1353" alt="image" src="https://github.com/YU000jp/logseq-page-tags-and-hierarchy/assets/12278003/669dd6bc-6369-4e02-aaa7-cfd3b6393670">

**Comment by YU000jp** [comment]
That's right. Thanks. I'll fix it when I have time.

**Comment by YU000jp** [comment]
I released a new version. https://github.com/YU000jp/logseq-page-tags-and-hierarchy/releases/tag/v2.18.6
Please let me know if there are any mistakes.

**Comment by zqinmiao** [comment]
> I released a new version. https://github.com/YU000jp/logseq-page-tags-and-hierarchy/releases/tag/v2.18.6 Please let me know if there are any mistakes.

fixed. Thank you.
