### ISSUE TITLE
Optimize for smaller screens

### ISSUE THREAD

**Issue by BravishkaSkytano** [YU000jp/logseq-page-tags-and-hierarchy#47]
I like the concept of the plugin, but it doesn't seem to work very well with smaller screens, like laptops with 10-inch screens. Could you add some CSS media queries or make it configurable in the plugin settings?

Thanks!

**Comment by YU000jp** [comment]
@BravishkaSkytano 
I have included the necessary changes in a new version and released it. See if it works with the window size you use most often. Please let me know if you still need to make changes.

**Comment by BravishkaSkytano** [comment]
I haven't tried my smaller screen yet, but it looks weird on my larger monitor. 
![IMG_20240115_153949624](https://github.com/YU000jp/logseq-page-tags-and-hierarchy/assets/65601594/eeb4b118-aa86-4e31-b904-4c5a66bb8756)

**Comment by YU000jp** [comment]
@BravishkaSkytano 
1. If your screen is small, use "Side" or "Bottom" instead of "Wide View". Currently, "Wide view" is designed with wide monitors in mind. 
1. (Table of Contents) It is a bug. I will try to fix it with CSS.
