### ISSUE TITLE
Crash app when trying to edit the title of a page that has a hierarchy and links to other pages in the title

### ISSUE THREAD

**Issue by mbelanger2** [YU000jp/logseq-page-tags-and-hierarchy#50]
logseq crash when trying to edit the title of a page that has links to other pages in the title. Logseq does not crash when the plugin isn't installed. 

By mistake (copy/paste), I created a page with links to other pages in the title. 
When I try to edit the title, logseq show the "Something went wrong" screen. 

1. Create a page named [[test/Level1]]
2. Create a page named [[[[test/Level1]] will it crash?]]
3. Open that last page
4. Try to edit the title.

I know that we don't need pages with links in the title. We should not be able to create them. But since we can, the plugin should no crash if it encounter them. 
![Logseq_hierarchyCrash](https://github.com/YU000jp/logseq-page-tags-and-hierarchy/assets/133134466/5e3cd329-6907-4170-8c87-0e86d2a4e4de)

**Comment by YU000jp** [comment]
It is a bug. Thank you for creating a screenshot that clearly reproduces the bug. I have a similar problem with unnecessary links. I would like to avoid crashes.

**Comment by YU000jp** [comment]
I released a new version. It will now be canceled if the page name contains "[[" and "]]". Thank you!

**Comment by YU000jp** [comment]
> In the future, I plan to create a plugin to delete pages with "[[" and "]]" in the page name. After 1 minute of the plugin running, it will delete those pages. Deletion will also occur after 1 hour. In this case, the page that contains "[[" and "]]" is assumed to be unnecessary and executed.

Add to `Innovation Lab` plugin
