### ISSUE TITLE
Suppport whiteboards

### ISSUE THREAD

**Issue by jh-devv** [YU000jp/logseq-page-tags-and-hierarchy#51]
Hey! @YU000jp 

I love your plugin and I have really enjoyed using it!

Though, when adding an page to an whiteboard, it does not separate the hierarchy part!

![problem](https://github.com/YU000jp/logseq-page-tags-and-hierarchy/assets/122896463/898b59fa-c047-4245-8765-17039c68f54c)
Here is an example ^

![logseq-whiteboard-hierarchy](https://github.com/YU000jp/logseq-page-tags-and-hierarchy/assets/122896463/fc504057-8e74-4e5e-850b-5b94e95b1aeb)
Here is how I would do it ^

Sincerely,
jh-devv

**Comment by YU000jp** [comment]
I want to make that happen too.
Since I am not a user of the whiteboard function, I will first need to recreate it based on the screenshots you provided and figure out the layout.
I will be working on this in between my business trips so progress will be a little slow.

**Comment by jh-devv** [comment]
> I want to make that happen too.
> Since I am not a user of the whiteboard function, I will first need to recreate it based on the screenshots you provided and figure out the layout.

Thanks!

> I will be working on this in between my business trips so progress will be a little slow.

No problem, take your time!

**Comment by jh-devv** [comment]
> I want to make that happen too.
> Since I am not a user of the whiteboard function, I will first need to recreate it based on the screenshots you provided and figure out the layout.

Thanks! @YU000jp 

> I will be working on this in between my business trips so progress will be a little slow.

No problem, take your time!

**Comment by YU000jp** [comment]
I made it like this.
![Logseqホワイトボード。階層分割](https://github.com/YU000jp/logseq-page-tags-and-hierarchy/assets/111847207/e39fcebf-cb13-4f69-b634-3fe6f7ca8cd1)

**Comment by YU000jp** [comment]
I released a new version. Please update, and let me know if it works as expected.

**Comment by jh-devv** [comment]
Yup! Thanks
