### ISSUE TITLE
Presence of the `tags::` property breaks the `Linked References` item

### ISSUE THREAD

**Issue by stdword** [YU000jp/logseq-page-tags-and-hierarchy#55]
## Demo
<img width="600px" src="https://github.com/user-attachments/assets/2b6adc48-ffc7-49a9-98bb-62f663f45c23"/>

## Notes
- It doesn't matter if page has namespace or not: `test/page` or `test-page`
- The console doesn't have any errors
- The only reason is the plugin turned on

**Comment by YU000jp** [comment]
In the plugin settings, uncheck “Omit the block if the Linked References contain tags property” toggle. A cleanup feature for users to use Linked References as a time series log, but it is still an incomplete feature. Sorry, it was on by default. This should be optional.
